/**
 * 种子工单数据 共 24 条 覆盖四态与五种售后类型
 * 为什么种子是纯函数且时间戳用固定基准: 重启后数据完全一致 便于 RPA 技能调试复现
 * 商品名里故意埋了广告法违禁词 全网最低 100%有效 国家级 第一 供后续风险扫描演示
 */
import type { Ticket } from './types'

// 种子定义 不含时间戳 时间戳由 seedTickets 统一生成
const seedDefs: Array<Omit<Ticket, 'createdAt' | 'updatedAt'>> = [
  {
    id: 'T0001',
    shopId: 'S001',
    shopName: '美妆旗舰店',
    orderNo: 'O202609280001',
    productName: '玻尿酸补水面膜 全网最低价',
    buyerNick: '小美',
    issueType: 'REFUND',
    status: 'PROCESSING',
    priority: 'HIGH',
    tags: ['过敏', '需核实'],
    refundAmount: 9900,
    refunded: false,
    description: '使用后脸部泛红 申请全额退款 附过敏照片',
  },
  {
    id: 'T0002',
    shopId: 'S001',
    shopName: '美妆旗舰店',
    orderNo: 'O202609280002',
    productName: '烟酰胺美白精华液',
    buyerNick: '爱美达人',
    issueType: 'REFUND',
    status: 'OPEN',
    priority: 'NORMAL',
    tags: [],
    refundAmount: 15900,
    refunded: false,
    description: '收到的精华液瓶口有漏液 要求退款',
  },
  {
    id: 'T0003',
    shopId: 'S001',
    shopName: '美妆旗舰店',
    orderNo: 'O202609270015',
    productName: '100%有效的祛痘膏',
    buyerNick: '痘哥',
    issueType: 'COMPLAINT',
    status: 'PROCESSING',
    priority: 'URGENT',
    tags: ['投诉', '敏感'],
    refundAmount: null,
    refunded: false,
    description: '宣传 100%有效 用了两周没效果 投诉虚假宣传',
  },
  {
    id: 'T0004',
    shopId: 'S001',
    shopName: '美妆旗舰店',
    orderNo: 'O202609260033',
    productName: '口红小样套装',
    buyerNick: '豆豆',
    issueType: 'RETURN',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已退货'],
    refundAmount: null,
    refunded: false,
    description: '颜色不适合 七天无理由退货 已寄回',
  },
  {
    id: 'T0005',
    shopId: 'S001',
    shopName: '美妆旗舰店',
    orderNo: 'O202609250021',
    productName: '防晒霜 国家级检测认证',
    buyerNick: '晴天',
    issueType: 'CONSULT',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已回复'],
    refundAmount: null,
    refunded: false,
    description: '咨询防晒霜孕妇能否使用 已回复',
  },
  {
    id: 'T0006',
    shopId: 'S002',
    shopName: '数码专营店',
    orderNo: 'O202609280101',
    productName: '无线降噪耳机 行业第一',
    buyerNick: '数码控',
    issueType: 'REFUND',
    status: 'PROCESSING',
    priority: 'HIGH',
    tags: ['质量差', '需核实'],
    refundAmount: 49900,
    refunded: false,
    description: '右耳有电流声 要求退款',
  },
  {
    id: 'T0007',
    shopId: 'S002',
    shopName: '数码专营店',
    orderNo: 'O202609270088',
    productName: '机械键盘 87 键',
    buyerNick: '码农老张',
    issueType: 'EXCHANGE',
    status: 'OPEN',
    priority: 'NORMAL',
    tags: [],
    refundAmount: null,
    refunded: false,
    description: '空格键回弹卡顿 申请换货',
  },
  {
    id: 'T0008',
    shopId: 'S002',
    shopName: '数码专营店',
    orderNo: 'O202609260056',
    productName: '便携充电宝 20000mAh',
    buyerNick: '旅行者',
    issueType: 'REFUND',
    status: 'REJECTED',
    priority: 'NORMAL',
    tags: ['已拒绝'],
    refundAmount: 12900,
    refunded: false,
    description: '充电速度慢 申请退款 因已过七天被驳回',
  },
  {
    id: 'T0009',
    shopId: 'S002',
    shopName: '数码专营店',
    orderNo: 'O202609250044',
    productName: '手机支架 桌面款',
    buyerNick: '追剧人',
    issueType: 'RETURN',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已退货', '已退款'],
    refundAmount: 3900,
    refunded: true,
    description: '尺寸不合适 退货并退款完成',
  },
  {
    id: 'T0010',
    shopId: 'S002',
    shopName: '数码专营店',
    orderNo: 'O202609240077',
    productName: '显示器 27 寸 4K',
    buyerNick: '设计师小王',
    issueType: 'COMPLAINT',
    status: 'PROCESSING',
    priority: 'URGENT',
    tags: ['投诉', '漏光'],
    refundAmount: null,
    refunded: false,
    description: '屏幕四角漏光严重 投诉质量问题',
  },
  {
    id: 'T0011',
    shopId: 'S003',
    shopName: '服饰旗舰店',
    orderNo: 'O202609280201',
    productName: '纯棉 T 恤 白色',
    buyerNick: '简约风',
    issueType: 'REFUND',
    status: 'OPEN',
    priority: 'NORMAL',
    tags: [],
    refundAmount: 5900,
    refunded: false,
    description: '尺码偏小 申请退款',
  },
  {
    id: 'T0012',
    shopId: 'S003',
    shopName: '服饰旗舰店',
    orderNo: 'O202609270192',
    productName: '牛仔外套 复古款',
    buyerNick: '潮人',
    issueType: 'EXCHANGE',
    status: 'PROCESSING',
    priority: 'NORMAL',
    tags: ['换大码'],
    refundAmount: null,
    refunded: false,
    description: '买小了 申请换大一号',
  },
  {
    id: 'T0013',
    shopId: 'S003',
    shopName: '服饰旗舰店',
    orderNo: 'O202609260150',
    productName: '运动卫衣 连帽',
    buyerNick: '健身达人',
    issueType: 'RETURN',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已退货'],
    refundAmount: null,
    refunded: false,
    description: '颜色与图片不符 已退货',
  },
  {
    id: 'T0014',
    shopId: 'S003',
    shopName: '服饰旗舰店',
    orderNo: 'O202609250139',
    productName: '针织开衫 女款',
    buyerNick: '温柔姐',
    issueType: 'CONSULT',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已回复'],
    refundAmount: null,
    refunded: false,
    description: '咨询起球问题 已回复',
  },
  {
    id: 'T0015',
    shopId: 'S003',
    shopName: '服饰旗舰店',
    orderNo: 'O202609240166',
    productName: '羽绒服 90 白鸭绒',
    buyerNick: '怕冷星人',
    issueType: 'COMPLAINT',
    status: 'REJECTED',
    priority: 'HIGH',
    tags: ['投诉', '已拒绝'],
    refundAmount: null,
    refunded: false,
    description: '投诉含绒量不足 检测达标 投诉驳回',
  },
  {
    id: 'T0016',
    shopId: 'S004',
    shopName: '食品旗舰店',
    orderNo: 'O202609280301',
    productName: '每日坚果 30 包',
    buyerNick: '零食控',
    issueType: 'REFUND',
    status: 'PROCESSING',
    priority: 'HIGH',
    tags: ['漏气', '需核实'],
    refundAmount: 9900,
    refunded: false,
    description: '多包坚果漏气 申请退款',
  },
  {
    id: 'T0017',
    shopId: 'S004',
    shopName: '食品旗舰店',
    orderNo: 'O202609270288',
    productName: '原切牛排 10 片',
    buyerNick: '大厨',
    issueType: 'COMPLAINT',
    status: 'OPEN',
    priority: 'URGENT',
    tags: ['变质', '投诉'],
    refundAmount: null,
    refunded: false,
    description: '收到时冰袋已化 牛排有异味 投诉',
  },
  {
    id: 'T0018',
    shopId: 'S004',
    shopName: '食品旗舰店',
    orderNo: 'O202609260245',
    productName: '有机纯牛奶 24 盒',
    buyerNick: '宝妈',
    issueType: 'REFUND',
    status: 'RESOLVED',
    priority: 'NORMAL',
    tags: ['已退款'],
    refundAmount: 6900,
    refunded: true,
    description: '部分牛奶包装破损 已退款',
  },
  {
    id: 'T0019',
    shopId: 'S004',
    shopName: '食品旗舰店',
    orderNo: 'O202609250221',
    productName: '手工曲奇饼干',
    buyerNick: '下午茶',
    issueType: 'CONSULT',
    status: 'RESOLVED',
    priority: 'LOW',
    tags: ['已回复'],
    refundAmount: null,
    refunded: false,
    description: '咨询保质期和储存方式 已回复',
  },
  {
    id: 'T0020',
    shopId: 'S005',
    shopName: '家居专营店',
    orderNo: 'O202609280401',
    productName: '乳胶枕头 泰国进口',
    buyerNick: '失眠患者',
    issueType: 'REFUND',
    status: 'OPEN',
    priority: 'NORMAL',
    tags: [],
    refundAmount: 19900,
    refunded: false,
    description: '味道刺鼻 申请退款',
  },
  {
    id: 'T0021',
    shopId: 'S005',
    shopName: '家居专营店',
    orderNo: 'O202609270388',
    productName: '四件套 全棉',
    buyerNick: '新家布置',
    issueType: 'EXCHANGE',
    status: 'PROCESSING',
    priority: 'NORMAL',
    tags: ['换花色'],
    refundAmount: null,
    refunded: false,
    description: '花色发错 申请换货',
  },
  {
    id: 'T0022',
    shopId: 'S005',
    shopName: '家居专营店',
    orderNo: 'O202609260355',
    productName: '懒人沙发 单人',
    buyerNick: '躺平青年',
    issueType: 'RETURN',
    status: 'REJECTED',
    priority: 'LOW',
    tags: ['已拒绝'],
    refundAmount: null,
    refunded: false,
    description: '觉得太小想退货 已过七天无理由期 驳回',
  },
  {
    id: 'T0023',
    shopId: 'S005',
    shopName: '家居专营店',
    orderNo: 'O202609250312',
    productName: '香薰蜡烛 三件套',
    buyerNick: '治愈系',
    issueType: 'CONSULT',
    status: 'OPEN',
    priority: 'LOW',
    tags: [],
    refundAmount: null,
    refunded: false,
    description: '咨询蜡烛燃烧时长 未回复',
  },
  {
    id: 'T0024',
    shopId: 'S005',
    shopName: '家居专营店',
    orderNo: 'O202609240300',
    productName: '实木书桌 1.2 米',
    buyerNick: '书房控',
    issueType: 'COMPLAINT',
    status: 'RESOLVED',
    priority: 'HIGH',
    tags: ['投诉', '已补偿'],
    refundAmount: null,
    refunded: false,
    description: '投诉桌角磕碰 已协商补偿 结案',
  },
]

/**
 * 生成种子工单 时间戳用固定基准加序号分钟 保证每次重启数据一致可复现
 * @returns 24 条工单数组
 */
export function seedTickets(): Ticket[] {
  const base = new Date('2026-09-28T08:00:00.000Z').getTime()

  return seedDefs.map((def, i) => {
    const created = base + i * 7 * 60 * 1000
    const updated = created + 5 * 60 * 1000
    return {
      ...def,
      createdAt: new Date(created).toISOString(),
      updatedAt: new Date(updated).toISOString(),
    }
  })
}
